import type { ServicePageData } from "@/components/sections/ServicePageTemplate";

export const serviceDataMap: Record<string, ServicePageData> = {
  "artificial-intelligence": {
    label: "AI Solutions",
    titlePre: "End-to-End",
    titleGradient: "Artificial Intelligence Solutions",
    headline: "Artificial Intelligence",
    heroDescription:
      "From AI strategy and model development to deployment and MLOps, ArlioTech delivers production-grade artificial intelligence systems that create genuine competitive advantage for your business.",
    description:
      "We design, develop, and deploy intelligent AI systems across the full spectrum — from custom model training to enterprise AI platforms that scale to millions of users.",
    gradient: "from-blue-500 to-purple-500",
    metrics: [
      { value: "200+", label: "AI systems deployed in production" },
      { value: "40%", label: "Average cost reduction achieved" },
      { value: "98%", label: "Client satisfaction rate" },
      { value: "6 weeks", label: "Average time to first working AI prototype" },
    ],
    technologies: ["TensorFlow", "PyTorch", "Hugging Face", "OpenAI", "LangChain", "MLflow", "FastAPI", "Kubernetes"],
    features: [
      { icon: "Brain", title: "Custom AI Model Development", description: "We build AI models from scratch or fine-tune foundation models for your specific domain, data, and business requirements." },
      { icon: "Layers", title: "AI Architecture & Strategy", description: "End-to-end AI roadmap design — model selection, infrastructure planning, data strategy, and ROI modeling before a single line of code." },
      { icon: "Network", title: "Neural Network Engineering", description: "Deep learning architectures for complex pattern recognition, sequence modeling, and multimodal AI applications." },
      { icon: "ShieldCheck", title: "Responsible AI & Governance", description: "Explainable AI, bias detection, fairness auditing, and governance frameworks that meet enterprise compliance standards." },
      { icon: "Gauge", title: "AI Performance Optimization", description: "Model quantization, distillation, and serving optimization to achieve production-grade speed at enterprise scale." },
      { icon: "RefreshCw", title: "MLOps & Continuous Learning", description: "Automated retraining pipelines, model monitoring, drift detection, and A/B testing infrastructure for self-improving AI systems." },
    ],
    process: [
      { step: "01", title: "AI Discovery", description: "Business problem mapping, data assessment, and opportunity prioritization." },
      { step: "02", title: "Model Design", description: "Architecture selection, baseline benchmarking, and experimentation planning." },
      { step: "03", title: "Development", description: "Iterative model training, evaluation, and fine-tuning with your data." },
      { step: "04", title: "Production Deployment", description: "Scalable serving infrastructure with monitoring and retraining pipelines." },
    ],
    useCases: [
      "Customer churn prediction",
      "Demand forecasting",
      "Intelligent document processing",
      "Recommendation systems",
      "Anomaly detection",
      "Natural language processing",
      "Process classification",
      "Risk scoring",
      "Sentiment analysis",
      "Entity extraction",
    ],
    faqs: [
      { q: "How long does a typical AI project take?", a: "Most production-ready AI projects take 8–16 weeks from discovery to deployment, depending on data availability and complexity. We deliver a working prototype within 6 weeks." },
      { q: "Do we need a large dataset to get started?", a: "Not necessarily. We assess your data during discovery and can often work with smaller datasets using transfer learning, synthetic data generation, or few-shot techniques." },
      { q: "Will we own the AI models built for us?", a: "Yes. All models, code, and intellectual property built for your project are fully owned by you upon project completion." },
      { q: "How do you ensure AI quality over time?", a: "We implement MLOps pipelines with drift detection, automated retraining triggers, and continuous monitoring dashboards so your models stay accurate as data evolves." },
    ],
  },

  "generative-ai": {
    label: "Generative AI",
    titlePre: "Build Products with",
    titleGradient: "Generative AI at Their Core",
    headline: "Generative AI",
    heroDescription:
      "ArlioTech is one of India's leading Generative AI studios. We build RAG systems, LLM-powered applications, AI copilots, and custom fine-tuned models that transform how your team works.",
    description:
      "We specialize in taking the latest LLMs — GPT-4, Claude, Gemini, Llama — and engineering them into reliable, secure, enterprise-grade applications with measurable ROI.",
    gradient: "from-purple-500 to-pink-500",
    metrics: [
      { value: "60+", label: "GenAI products launched" },
      { value: "10x", label: "Productivity gains for knowledge workers" },
      { value: "90%", label: "Reduction in manual document processing" },
      { value: "3 weeks", label: "To production-ready GenAI prototype" },
    ],
    technologies: ["OpenAI GPT-4", "Claude", "Gemini", "Llama 3", "LangChain", "LlamaIndex", "Pinecone", "FAISS", "Weaviate"],
    features: [
      { icon: "FileText", title: "RAG Systems", description: "Retrieval-Augmented Generation systems that ground LLMs in your private knowledge bases, delivering accurate, hallucination-resistant answers." },
      { icon: "Cpu", title: "LLM Fine-tuning", description: "Custom fine-tuning of open and proprietary models on your domain-specific data for superior performance on niche tasks." },
      { icon: "Bot", title: "AI Copilots & Assistants", description: "Context-aware AI copilots for coding, writing, analysis, customer support, and complex enterprise workflows." },
      { icon: "Search", title: "Semantic Search", description: "Vector-based semantic search that understands meaning — not just keywords — across documents, products, and knowledge bases." },
      { icon: "Workflow", title: "Agentic Pipelines", description: "Multi-step LLM pipelines that plan, reason, use tools, and execute complex tasks autonomously with human oversight." },
      { icon: "Lock", title: "Private & Secure Deployment", description: "On-premise or VPC-isolated deployments ensuring your sensitive data never leaves your infrastructure." },
    ],
    process: [
      { step: "01", title: "Use Case Design", description: "Identify highest-ROI GenAI applications for your business and select optimal models." },
      { step: "02", title: "Data & Embedding", description: "Index your knowledge base, build vector stores, and design retrieval strategies." },
      { step: "03", title: "Prompt Engineering", description: "Systematic prompt optimization and guardrail implementation for reliable outputs." },
      { step: "04", title: "Production & Scale", description: "Deploy with caching, rate limiting, monitoring, and cost optimization in place." },
    ],
    useCases: [
      "Enterprise knowledge base chatbot",
      "AI-powered document summarization",
      "Contract review automation",
      "Code generation assistant",
      "Personalized content generation",
      "Customer support automation",
      "Financial report generation",
      "Meeting intelligence & summarization",
      "HR policy chatbot",
      "AI-powered product descriptions",
    ],
    faqs: [
      { q: "Which LLM should we use for our product?", a: "It depends on your accuracy, latency, cost, and privacy requirements. We evaluate GPT-4, Claude, Gemini, and open-source models like Llama during discovery to recommend the best fit." },
      { q: "How do you prevent hallucinations?", a: "We use RAG architectures, structured output validation, confidence thresholds, and citation-grounding to minimize hallucinations in production GenAI systems." },
      { q: "Is our data safe when using third-party LLM APIs?", a: "We implement data anonymization, PII masking, and can deploy fully private on-premise LLMs for regulated industries where data sovereignty is critical." },
      { q: "What does fine-tuning cost compared to RAG?", a: "RAG is faster and cheaper to build but requires good retrieval infrastructure. Fine-tuning delivers higher task-specific accuracy but takes 2–4 weeks and requires quality training data. We'll recommend the right approach for your budget and performance targets." },
    ],
  },

  "automation": {
    label: "Automation & RPA",
    titlePre: "Automate Smarter with",
    titleGradient: "AI-Powered RPA",
    headline: "Intelligent Automation",
    heroDescription:
      "We combine traditional RPA with AI — document understanding, NLP, and decision intelligence — to create automation that handles the messy, exception-heavy workflows traditional bots can't touch.",
    description:
      "Intelligent automation that goes beyond simple rule-based bots. Our AI-enhanced RPA solutions handle unstructured data, make intelligent decisions, and continuously improve.",
    gradient: "from-yellow-500 to-orange-500",
    metrics: [
      { value: "75%", label: "Reduction in manual processing time" },
      { value: "99.5%", label: "Process accuracy rate" },
      { value: "6 months", label: "Average payback period" },
      { value: "24/7", label: "Uninterrupted process execution" },
    ],
    technologies: ["UiPath", "Power Automate", "n8n", "Zapier", "Make.com", "Python", "AI/ML Models", "OCR"],
    features: [
      { icon: "Workflow", title: "Intelligent Document Processing", description: "AI that reads, understands, and extracts data from invoices, contracts, forms, and unstructured documents with human-level accuracy." },
      { icon: "Bot", title: "AI-Enhanced RPA Bots", description: "Traditional RPA bots augmented with computer vision, NLP, and decision-making AI to handle complex, exception-heavy workflows." },
      { icon: "PlugZap", title: "API & System Integration", description: "Seamless automation across your ERP, CRM, HRMS, and custom applications — connecting disparate systems into unified workflows." },
      { icon: "LineChart", title: "Process Mining & Analysis", description: "AI-powered process discovery that maps your current workflows, identifies bottlenecks, and recommends automation opportunities." },
      { icon: "RefreshCw", title: "Self-Healing Automation", description: "Bots that detect and recover from exceptions autonomously, minimizing human intervention and maximizing uptime." },
      { icon: "Gauge", title: "Orchestration & Monitoring", description: "Centralized automation management, real-time monitoring, SLA tracking, and performance analytics dashboards." },
    ],
    process: [
      { step: "01", title: "Process Assessment", description: "Map current workflows, identify automation candidates, and calculate ROI projections." },
      { step: "02", title: "Solution Design", description: "Architecture the automation — selecting tools, designing exception handling, and planning integrations." },
      { step: "03", title: "Build & Test", description: "Develop automation with parallel testing to validate accuracy, performance, and edge case handling." },
      { step: "04", title: "Deploy & Optimize", description: "Production rollout with monitoring, exception queue management, and continuous improvement." },
    ],
    useCases: [
      "Invoice processing automation",
      "Employee onboarding workflows",
      "Order-to-cash automation",
      "HR process automation",
      "Compliance report generation",
      "Data migration & synchronization",
      "Customer onboarding",
      "Claims processing",
      "Regulatory reporting",
      "Inventory reconciliation",
    ],
    faqs: [
      { q: "What's the difference between RPA and AI-powered automation?", a: "Traditional RPA follows rigid rules and breaks when screen layouts change. AI-powered automation understands context, handles unstructured data, and adapts to variations — dramatically expanding what can be automated." },
      { q: "How quickly can we see ROI from automation?", a: "Most of our clients achieve full payback within 6 months. Simpler automations can pay back in weeks. We calculate ROI projections during the assessment phase before any development starts." },
      { q: "Which processes are best suited for automation?", a: "High-volume, repetitive, rule-based tasks with structured inputs are ideal. Invoice processing, data entry, report generation, and system integrations are among the highest-ROI starting points." },
      { q: "What happens when a bot encounters an exception it can't handle?", a: "We design intelligent exception handling with automatic escalation to human queues, full audit trails, and self-healing mechanisms that learn from resolved exceptions over time." },
    ],
  },

  "cloud-solutions": {
    label: "Cloud Solutions",
    titlePre: "Cloud-Native AI Infrastructure",
    titleGradient: "Built for Scale",
    headline: "Cloud Architecture",
    heroDescription:
      "We design, migrate, and optimize cloud infrastructure for AI workloads — building scalable, cost-optimized environments on AWS, Azure, and GCP that power your intelligent systems.",
    description:
      "Multi-cloud expertise combined with deep AI infrastructure knowledge. We build the cloud foundation your AI systems need to perform at enterprise scale.",
    gradient: "from-cyan-500 to-blue-500",
    metrics: [
      { value: "35%", label: "Average cloud cost reduction" },
      { value: "99.99%", label: "Uptime SLA achieved" },
      { value: "10x", label: "Infrastructure scalability improvement" },
      { value: "50+", label: "Cloud migrations completed" },
    ],
    technologies: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Docker", "Helm", "Prometheus", "Grafana"],
    features: [
      { icon: "Server", title: "Cloud Architecture Design", description: "Multi-cloud and hybrid cloud architectures designed for AI workloads — GPU clusters, distributed training, and high-throughput inference serving." },
      { icon: "Settings", title: "Cloud Migration", description: "Lift-and-shift, re-architecture, and cloud-native transformation. We migrate complex legacy systems with zero-downtime strategies." },
      { icon: "Lock", title: "Cloud Security & Compliance", description: "Zero-trust security models, IAM configuration, data encryption, and compliance automation for regulated industries." },
      { icon: "Gauge", title: "Cost Optimization", description: "FinOps practices, right-sizing, reserved capacity planning, and automated cost anomaly detection to minimize cloud spend." },
      { icon: "RefreshCw", title: "CI/CD & DevOps", description: "Modern DevOps pipelines, GitOps workflows, and infrastructure-as-code for reliable, reproducible deployments." },
      { icon: "LineChart", title: "Observability & Monitoring", description: "Full-stack observability with distributed tracing, metrics, logs, and intelligent alerting for proactive incident management." },
    ],
    process: [
      { step: "01", title: "Cloud Assessment", description: "Evaluate current infrastructure, map workloads, and design cloud adoption strategy." },
      { step: "02", title: "Architecture Design", description: "Design target-state cloud architecture with security, compliance, and cost frameworks." },
      { step: "03", title: "Migration & Build", description: "Phased migration or greenfield build with continuous testing and validation." },
      { step: "04", title: "Optimize & Operate", description: "Post-migration optimization, cost tuning, and ongoing managed operations." },
    ],
    useCases: [
      "AI/ML model training infrastructure",
      "Scalable inference serving",
      "Data lake & warehouse setup",
      "Legacy application modernization",
      "Multi-region deployment",
      "Disaster recovery setup",
      "Kubernetes migration",
      "Serverless architecture",
      "Edge computing deployment",
      "Cloud cost optimization",
    ],
    faqs: [
      { q: "Which cloud provider do you recommend — AWS, Azure, or GCP?", a: "It depends on your existing stack, team familiarity, and workload type. AWS leads in breadth of services, Azure suits Microsoft-centric organizations, and GCP excels for AI/ML workloads. We help you evaluate and often design multi-cloud strategies." },
      { q: "How do you minimize downtime during cloud migration?", a: "We use phased migration strategies — strangler fig patterns, blue-green deployments, and traffic shifting — to migrate complex systems with zero or near-zero downtime even for mission-critical applications." },
      { q: "Can you help reduce our existing cloud bill?", a: "Yes. Cloud cost optimization is a standalone engagement we offer. Common wins include right-sizing compute, implementing auto-scaling, moving to reserved/spot instances, and eliminating unused resources — typically yielding 25–40% savings." },
      { q: "What compliance certifications do you support?", a: "We have experience with SOC 2, ISO 27001, HIPAA, PCI-DSS, and GDPR cloud compliance frameworks. We automate compliance checks and implement guardrails as code using tools like AWS Config and Azure Policy." },
    ],
  },

  "machine-learning": {
    label: "Machine Learning",
    titlePre: "Production",
    titleGradient: "Machine Learning at Enterprise Scale",
    headline: "Machine Learning",
    heroDescription:
      "We build end-to-end ML pipelines — data preprocessing, feature engineering, model training, evaluation, and production deployment — with rigorous MLOps practices for long-term reliability.",
    description:
      "From exploratory data analysis to model serving at scale, we handle every stage of the ML lifecycle with engineering rigor and business focus.",
    gradient: "from-green-500 to-cyan-500",
    metrics: [
      { value: "85+", label: "ML models in production" },
      { value: "3-5x", label: "Model performance vs. baseline" },
      { value: "60%", label: "Faster model iteration cycles" },
      { value: "99.9%", label: "Model serving uptime" },
    ],
    technologies: ["Python", "Scikit-learn", "PyTorch", "TensorFlow", "XGBoost", "MLflow", "DVC", "Feast", "Seldon"],
    features: [
      { icon: "FlaskConical", title: "Experimentation Framework", description: "Systematic ML experimentation with versioned datasets, tracked experiments, and reproducible results using MLflow and DVC." },
      { icon: "BarChart3", title: "Feature Engineering", description: "Advanced feature stores, automated feature selection, and real-time feature serving infrastructure for production ML." },
      { icon: "GitBranch", title: "Model Version Control", description: "Complete model lineage tracking, A/B testing infrastructure, and canary deployment strategies for safe production rollouts." },
      { icon: "Gauge", title: "Model Monitoring", description: "Data drift detection, model performance tracking, and automated retraining triggers to keep models accurate over time." },
      { icon: "TrendingUp", title: "AutoML Capabilities", description: "Automated hyperparameter optimization, neural architecture search, and ensemble methods to accelerate model development." },
      { icon: "Server", title: "Scalable Serving", description: "Low-latency, high-throughput model serving with batch prediction, real-time inference, and streaming prediction capabilities." },
    ],
    process: [
      { step: "01", title: "Problem Framing", description: "Define ML objectives, success metrics, baseline benchmarks, and data requirements." },
      { step: "02", title: "Data Pipeline", description: "Build data ingestion, cleaning, transformation, and feature engineering pipelines." },
      { step: "03", title: "Model Development", description: "Iterative training, evaluation, and optimization with experiment tracking." },
      { step: "04", title: "Production MLOps", description: "Deploy with monitoring, automated retraining, and CI/CD for ML models." },
    ],
    useCases: [
      "Customer lifetime value prediction",
      "Price optimization",
      "Credit risk scoring",
      "Energy consumption forecasting",
      "Product recommendation",
      "Churn prediction",
      "Supply chain optimization",
      "Medical diagnosis support",
      "Equipment failure prediction",
      "Lead scoring",
    ],
    faqs: [
      { q: "How much data do we need to train a useful ML model?", a: "It varies by problem type. Classification tasks can work with a few thousand examples; complex forecasting may need years of history. We assess your data during discovery and advise whether to collect more, use transfer learning, or apply data augmentation." },
      { q: "How do you ensure models don't degrade over time in production?", a: "We implement continuous monitoring for data drift and concept drift, automated retraining pipelines triggered by performance thresholds, and shadow deployment to validate new model versions before swapping." },
      { q: "What's the difference between ML and AI?", a: "Machine learning is a subset of AI where systems learn patterns from data rather than following explicit rules. AI is the broader field. Most practical AI systems today use ML as their core engine." },
      { q: "Can you improve an existing ML model we already have?", a: "Yes — model improvement engagements are common. We audit your current model's training data, feature engineering, architecture, and evaluation methodology, then implement targeted improvements that typically yield 20–50% performance gains." },
    ],
  },

  "computer-vision": {
    label: "Computer Vision",
    titlePre: "Visual AI That Sees What",
    titleGradient: "Humans Miss",
    headline: "Computer Vision",
    heroDescription:
      "From quality control cameras on factory floors to medical imaging analysis in hospitals, we build computer vision systems that process visual information faster, more accurately, and at scale.",
    description:
      "State-of-the-art vision AI built with the latest deep learning architectures — deployed at the edge, in the cloud, or in hybrid environments for real-time performance.",
    gradient: "from-indigo-500 to-purple-500",
    metrics: [
      { value: "99.4%", label: "Defect detection accuracy" },
      { value: "30ms", label: "Inference latency (edge)" },
      { value: "65%", label: "QC cost reduction" },
      { value: "24/7", label: "Continuous visual monitoring" },
    ],
    technologies: ["YOLOv9", "OpenCV", "PyTorch", "TensorRT", "ONNX", "AWS Rekognition", "Azure Vision", "MediaPipe"],
    features: [
      { icon: "Eye", title: "Object Detection & Tracking", description: "Real-time multi-object detection, classification, and tracking using state-of-the-art YOLO and transformer-based architectures." },
      { icon: "Search", title: "Defect Detection & QC", description: "Industrial-grade visual inspection systems that catch defects human inspectors miss, operating 24/7 on production lines." },
      { icon: "Image", title: "Image Classification & Segmentation", description: "Pixel-level semantic and instance segmentation for medical imaging, satellite analysis, and fine-grained categorization." },
      { icon: "Users", title: "Face Recognition & Analysis", description: "Secure, privacy-compliant facial recognition, emotion detection, and biometric authentication systems." },
      { icon: "FileText", title: "OCR & Document Intelligence", description: "Intelligent character recognition that understands context — extracting structured data from complex documents, forms, and receipts." },
      { icon: "Monitor", title: "Video Analytics", description: "Real-time video analysis for security, retail behavior analytics, traffic management, and workplace safety monitoring." },
    ],
    process: [
      { step: "01", title: "Data Collection", description: "Design data acquisition strategy, annotation pipeline, and training data validation." },
      { step: "02", title: "Model Architecture", description: "Select and customize vision architectures based on accuracy, speed, and deployment requirements." },
      { step: "03", title: "Training & Tuning", description: "Train with domain-specific data, handle class imbalance, and optimize for target performance metrics." },
      { step: "04", title: "Edge/Cloud Deploy", description: "Optimize and deploy models for edge devices, GPUs, or cloud APIs with monitoring in place." },
    ],
    useCases: [
      "Manufacturing quality control",
      "Medical image analysis",
      "Retail shelf monitoring",
      "Security & surveillance AI",
      "License plate recognition",
      "Crop disease detection",
      "Construction site safety",
      "Document digitization",
      "Retail customer behavior analytics",
      "Autonomous vehicle perception",
    ],
    faqs: [
      { q: "How much labeled image data do we need?", a: "For transfer learning from pretrained models, a few hundred labeled images per class can be sufficient. For highly specialized domains or very high accuracy requirements, we recommend 1,000–10,000 examples per class. We also offer data augmentation and synthetic data generation." },
      { q: "Can computer vision work in real time on edge devices?", a: "Yes. We use model optimization techniques like quantization, pruning, and TensorRT acceleration to deploy high-accuracy vision models on edge hardware including NVIDIA Jetson, Raspberry Pi, and industrial PLCs with sub-50ms latency." },
      { q: "How do you handle privacy concerns with facial recognition?", a: "We design systems with privacy by default — on-device processing to avoid transmitting images, biometric data hashing, consent management, and compliance with GDPR and India's DPDP Act. We can also build systems that detect presence without identifying individuals." },
      { q: "What accuracy can we expect for defect detection?", a: "Our industrial inspection systems consistently achieve 98–99.5% accuracy, often outperforming human inspectors who fatigue over long shifts. We target your specific false positive / false negative trade-off during the design phase." },
    ],
  },

  "data-engineering": {
    label: "Data Engineering",
    titlePre: "Modern Data Platforms That",
    titleGradient: "Power Your AI",
    headline: "Data Engineering",
    heroDescription:
      "Without clean, well-organized data, AI fails. We build the data foundations — ETL pipelines, data lakes, feature stores, and real-time streaming architectures — that make AI possible.",
    description:
      "End-to-end data engineering from raw ingestion to analytics-ready data products. We specialize in modern data stack architectures that scale with your business.",
    gradient: "from-teal-500 to-cyan-500",
    metrics: [
      { value: "10x", label: "Data pipeline performance improvement" },
      { value: "99.9%", label: "Data availability SLA" },
      { value: "50%", label: "Reduction in data preparation time" },
      { value: "Real-time", label: "Sub-second latency achievable" },
    ],
    technologies: ["Apache Spark", "dbt", "Snowflake", "BigQuery", "Kafka", "Airflow", "Databricks", "dlt", "Fivetran"],
    features: [
      { icon: "Database", title: "Data Lake Architecture", description: "Modern lake house architectures on Delta Lake, Apache Iceberg, or Hudi — combining the flexibility of data lakes with the reliability of warehouses." },
      { icon: "Workflow", title: "ETL/ELT Pipelines", description: "Reliable, observable data pipelines with automated testing, alerting, and lineage tracking using dbt, Spark, and Airflow." },
      { icon: "Gauge", title: "Real-time Streaming", description: "Event-driven data architectures with Apache Kafka, Flink, or Kinesis for millisecond-latency data processing at scale." },
      { icon: "Package", title: "Feature Store", description: "Centralized feature stores for ML — ensuring consistent feature computation between training and serving environments." },
      { icon: "PieChart", title: "Analytics Engineering", description: "dbt-based analytics engineering that transforms raw data into clean, documented, tested data models for BI and AI." },
      { icon: "LineChart", title: "Data Observability", description: "End-to-end data quality monitoring, anomaly detection, and SLA tracking to ensure AI systems get clean, reliable data." },
    ],
    process: [
      { step: "01", title: "Data Audit", description: "Map existing data sources, assess quality, identify gaps, and design target architecture." },
      { step: "02", title: "Pipeline Design", description: "Architect ingestion, transformation, and serving layers with scalability and reliability in mind." },
      { step: "03", title: "Build & Test", description: "Develop pipelines with unit tests, data quality checks, and monitoring from day one." },
      { step: "04", title: "Operate & Scale", description: "Production deployment with observability, alerting, and iterative capacity planning." },
    ],
    useCases: [
      "Centralized data platform build",
      "Legacy data warehouse migration",
      "Real-time analytics pipeline",
      "ML feature store implementation",
      "Multi-source data integration",
      "IoT data processing",
      "Customer 360 data model",
      "Financial reporting automation",
      "Data governance implementation",
      "Self-serve analytics platform",
    ],
    faqs: [
      { q: "Should we build a data warehouse or data lake?", a: "Modern organizations benefit from a lakehouse — combining the raw data flexibility of lakes with the governance and query performance of warehouses. Tools like Snowflake, Databricks, and BigQuery blur this distinction. We'll recommend the right architecture for your scale and use cases." },
      { q: "How do you ensure data quality in pipelines?", a: "We implement data quality checks at every layer using dbt tests, Great Expectations, and custom validation rules. Failed quality checks trigger alerts and halt downstream pipelines, preventing bad data from reaching analytics or AI systems." },
      { q: "What is a modern data stack?", a: "The modern data stack typically includes a cloud data warehouse (Snowflake/BigQuery), an ELT ingestion tool (Fivetran/dlt), a transformation layer (dbt), and a BI/analytics tool (Looker/Metabase). We design, build, and operate this stack end-to-end." },
      { q: "How do you handle streaming vs batch data?", a: "We design unified architectures — often using Apache Kafka for real-time streams and Spark/Airflow for batch — with a shared data model so both converge in the same warehouse or lake for consistent analytics." },
    ],
  },

  "web-development": {
    label: "Web Development",
    titlePre: "High-Performance Web Apps",
    titleGradient: "Built for the AI Era",
    headline: "Web Development",
    heroDescription:
      "We build fast, SEO-optimized, accessible web applications that serve as the front door to your AI products. From marketing sites to complex AI-powered web platforms.",
    description:
      "Modern web development with Next.js, React, and TypeScript. Every application is performance-first, mobile-optimized, and production-ready from day one.",
    gradient: "from-blue-500 to-cyan-500",
    metrics: [
      { value: "95+", label: "Lighthouse performance score" },
      { value: "<100ms", label: "Server response time (p95)" },
      { value: "100+", label: "Web projects delivered" },
      { value: "Core Web Vitals", label: "Consistently green" },
    ],
    technologies: ["Next.js 15", "React", "TypeScript", "Tailwind CSS", "Node.js", "PostgreSQL", "Prisma", "Vercel"],
    features: [
      { icon: "Rocket", title: "Next.js 15 Applications", description: "App Router, Server Components, streaming, and edge functions — built with the latest Next.js for maximum performance and developer experience." },
      { icon: "Globe", title: "SEO & Core Web Vitals", description: "Semantic HTML, structured data, sitemap generation, and technical SEO built in from the start. We deliver Lighthouse 95+ scores." },
      { icon: "Palette", title: "Premium UI/UX Integration", description: "Pixel-perfect implementation of design systems with smooth animations, micro-interactions, and responsive layouts for all screen sizes." },
      { icon: "Lock", title: "Security & Authentication", description: "Enterprise-grade authentication with NextAuth, JWT, OAuth2, and fine-grained authorization — built securely from the ground up." },
      { icon: "Server", title: "API Development", description: "RESTful and GraphQL APIs, tRPC type-safe endpoints, and seamless integration with third-party services and AI backends." },
      { icon: "LineChart", title: "Analytics & Optimization", description: "Conversion rate optimization, A/B testing infrastructure, and analytics integration for data-driven continuous improvement." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "Define requirements, user journeys, and technical architecture." },
      { step: "02", title: "Design & Prototype", description: "UI/UX design, component library, and interactive prototypes." },
      { step: "03", title: "Development", description: "Agile sprints with weekly demos, testing, and CI/CD deployment." },
      { step: "04", title: "Launch & Optimize", description: "SEO audit, performance optimization, and post-launch monitoring." },
    ],
    useCases: [
      "SaaS product development",
      "Corporate marketing websites",
      "E-commerce platforms",
      "AI product portals",
      "Customer dashboards",
      "Partner portals",
      "Content management systems",
      "Progressive web apps",
      "Landing page systems",
      "Web application redesign",
    ],
    faqs: [
      { q: "Why Next.js over other React frameworks?", a: "Next.js 15 with the App Router gives us React Server Components, streaming SSR, edge rendering, and first-class TypeScript support — resulting in faster pages, better SEO, and a superior developer experience compared to alternatives like Remix or CRA." },
      { q: "How do you ensure fast page load times?", a: "We combine Next.js server-side rendering with image optimization, font subsetting, code splitting, edge caching, and Core Web Vitals monitoring. Our apps routinely score 95+ on Lighthouse and pass all Core Web Vitals thresholds." },
      { q: "Do you handle hosting and deployment?", a: "Yes. We set up CI/CD pipelines with GitHub Actions, deploy to Vercel or AWS, configure CDN caching, and can provide ongoing managed hosting with uptime monitoring and alerting." },
      { q: "How long does a typical web project take?", a: "A marketing website takes 3–6 weeks. A complex SaaS product with authentication, dashboards, and integrations typically takes 10–16 weeks. We scope precisely during discovery so you always know the timeline before we start." },
    ],
  },

  "mobile-app-development": {
    label: "Mobile Development",
    titlePre: "Native Mobile Apps with",
    titleGradient: "AI Built In",
    headline: "Mobile Development",
    heroDescription:
      "We build high-performance iOS and Android applications — native and cross-platform — that incorporate AI features like on-device ML, conversational interfaces, and smart personalization.",
    description:
      "Mobile-first thinking with AI-first features. Our mobile apps deliver exceptional user experiences with the intelligence users now expect.",
    gradient: "from-violet-500 to-purple-500",
    metrics: [
      { value: "4.8★", label: "Average App Store rating" },
      { value: "60+", label: "Mobile apps delivered" },
      { value: "40%", label: "Development cost savings (cross-platform)" },
      { value: "<2s", label: "App launch time target" },
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "RevenueCat", "Core ML"],
    features: [
      { icon: "Smartphone", title: "React Native & Flutter", description: "Cross-platform mobile development that delivers near-native performance with shared codebases — reducing time and cost without sacrificing quality." },
      { icon: "Brain", title: "On-Device AI/ML", description: "Integrate Core ML, TensorFlow Lite, and on-device models for AI features that work offline — privacy-preserving and ultra-fast." },
      { icon: "Mic", title: "Voice & Conversational AI", description: "Natural language interfaces, voice commands, and AI chat features that make mobile apps genuinely intelligent and hands-free." },
      { icon: "Users", title: "Personalization Engine", description: "Behavioral AI that learns user preferences to deliver hyper-personalized content, notifications, and product recommendations." },
      { icon: "Lock", title: "Security & Biometrics", description: "Biometric authentication, encrypted local storage, certificate pinning, and mobile-specific security hardening for enterprise apps." },
      { icon: "LineChart", title: "Analytics & Crashlytics", description: "User behavior analytics, funnel tracking, crash reporting, and performance monitoring for continuous mobile optimization." },
    ],
    process: [
      { step: "01", title: "Product Discovery", description: "User research, feature prioritization, and mobile-specific UX strategy." },
      { step: "02", title: "UI/UX Design", description: "Platform-specific design patterns, interactive prototyping, and usability testing." },
      { step: "03", title: "Development", description: "Agile sprints with bi-weekly TestFlight/Play Store builds and rapid iteration." },
      { step: "04", title: "Launch & ASO", description: "App Store submission, ASO optimization, and post-launch growth tracking." },
    ],
    useCases: [
      "Consumer mobile product",
      "Enterprise mobile app",
      "AI-powered utility app",
      "HealthTech mobile app",
      "FinTech mobile application",
      "On-demand service app",
      "EdTech learning app",
      "IoT control application",
      "E-commerce mobile app",
      "Field service app",
    ],
    faqs: [
      { q: "Should we build native iOS/Android or go cross-platform?", a: "For most products, React Native or Flutter delivers 95% of native performance at 40–60% of the cost. We recommend native Swift/Kotlin only when you need deep platform integration (AR, advanced graphics, hardware accessories) or maximum performance is critical." },
      { q: "How do you handle App Store and Play Store submission?", a: "We manage the full submission process — preparing assets, writing ASO-optimized descriptions, configuring in-app purchases, setting up TestFlight/beta testing, and navigating review guidelines to maximize approval speed." },
      { q: "Can you add AI features to our existing app?", a: "Yes. We can integrate on-device ML models, LLM-powered chat, recommendation engines, and smart search into existing React Native, Flutter, or native apps without a full rewrite." },
      { q: "How do you ensure our app performs well on older devices?", a: "We set minimum OS targets during discovery, profile performance on representative low-end devices, implement lazy loading and image optimization, and use on-device model quantization to keep AI features fast on older hardware." },
    ],
  },

  "ui-ux-design": {
    label: "UI/UX Design",
    titlePre: "Premium Design That",
    titleGradient: "Converts and Delights",
    headline: "UI/UX Design",
    heroDescription:
      "We craft interfaces that users love and businesses profit from. Our research-driven design process combines aesthetic excellence with conversion science to build products that perform.",
    description:
      "From design systems to interactive prototypes, we deliver premium UI/UX that elevates your brand and drives measurable business outcomes.",
    gradient: "from-pink-500 to-rose-500",
    metrics: [
      { value: "35%", label: "Average conversion rate improvement" },
      { value: "70%", label: "Reduction in support tickets via better UX" },
      { value: "4.9★", label: "Design satisfaction score" },
      { value: "50+", label: "Design projects completed" },
    ],
    technologies: ["Figma", "Framer", "Adobe XD", "Storybook", "Tailwind CSS", "Framer Motion", "Lottie", "Principle"],
    features: [
      { icon: "Search", title: "User Research & Testing", description: "User interviews, usability testing, heuristic evaluation, and data-informed design decisions that solve real user problems." },
      { icon: "Palette", title: "Design Systems", description: "Scalable, tokenized design systems with component libraries, guidelines, and documentation that enable consistent product development." },
      { icon: "Monitor", title: "Web & App UI Design", description: "Pixel-perfect, responsive designs for web and mobile — from wireframes to high-fidelity mockups with micro-interaction specifications." },
      { icon: "Rocket", title: "Interactive Prototyping", description: "High-fidelity, interactive prototypes that feel like the real product — used for stakeholder alignment and user validation." },
      { icon: "LineChart", title: "Conversion Optimization", description: "Data-driven UX optimization — heatmap analysis, A/B testing, funnel optimization, and landing page design that converts." },
      { icon: "Brain", title: "AI Interface Design", description: "Specialized expertise in designing for AI — trust signals, loading states, confidence indicators, and AI-human interaction patterns." },
    ],
    process: [
      { step: "01", title: "Discovery", description: "Stakeholder workshops, competitor analysis, and user persona development." },
      { step: "02", title: "Information Architecture", description: "Sitemap design, user flow mapping, and content hierarchy." },
      { step: "03", title: "Design & Iterate", description: "Wireframes → visual design → prototype → user testing cycles." },
      { step: "04", title: "Handoff", description: "Developer handoff with Figma specs, design tokens, and documentation." },
    ],
    useCases: [
      "SaaS product redesign",
      "AI product interface design",
      "Mobile app UX design",
      "E-commerce UX optimization",
      "Design system creation",
      "Brand identity design",
      "Dashboard & data visualization",
      "Landing page design",
      "Design audit & CRO",
      "Prototype for investor pitch",
    ],
    faqs: [
      { q: "Do you do brand identity design as well?", a: "Yes. Our design practice covers brand identity — logo, color palette, typography, and brand guidelines — through to product UI/UX. We can handle the full visual expression of your brand." },
      { q: "How do you measure the success of design work?", a: "We define success metrics upfront — conversion rates, task completion rates, NPS, time-on-task — and validate designs through user testing before handoff. Post-launch, we track these metrics and iterate." },
      { q: "What do you deliver at the end of a design project?", a: "A fully specified Figma design file with component libraries, responsive layouts, interaction notes, design tokens, and a handoff guide. For design systems, we also deliver Storybook documentation and CSS/Tailwind token files." },
      { q: "Can you work with our existing design system?", a: "Absolutely. We routinely extend, audit, and evolve existing design systems. We'll work within your constraints while identifying opportunities to improve consistency, accessibility, and developer ergonomics." },
    ],
  },

  "chatbot-development": {
    label: "Chatbot Development",
    titlePre: "Conversational AI That",
    titleGradient: "Understands Your Business",
    headline: "Conversational AI",
    heroDescription:
      "We build intelligent chatbots and virtual assistants that handle real conversations — not just scripts. Powered by the latest LLMs with deep business logic integration.",
    description:
      "From customer support bots to internal knowledge assistants, our conversational AI solutions drive engagement, reduce costs, and scale your team's capabilities.",
    gradient: "from-emerald-500 to-teal-500",
    metrics: [
      { value: "80%", label: "Query deflection from human agents" },
      { value: "94%", label: "Customer satisfaction (CSAT)" },
      { value: "3 min", label: "Average response time reduction" },
      { value: "24/7", label: "Always-on customer engagement" },
    ],
    technologies: ["OpenAI", "Claude", "LangChain", "Rasa", "WhatsApp Business API", "Dialogflow", "Twilio", "Zendesk"],
    features: [
      { icon: "MessageSquare", title: "LLM-Powered Chatbots", description: "Chatbots powered by GPT-4, Claude, or fine-tuned open-source models that understand context, handle complex queries, and maintain conversation history." },
      { icon: "Globe", title: "Omnichannel Deployment", description: "Deploy across web, WhatsApp, Telegram, Slack, Teams, Instagram, and your CRM — unified conversation management across all channels." },
      { icon: "Brain", title: "Domain-Specific Training", description: "Chatbots fine-tuned on your product documentation, FAQ, and business processes — delivering accurate, brand-consistent responses." },
      { icon: "Users", title: "Human Handoff", description: "Intelligent escalation to human agents with full conversation context, sentiment analysis, and CSAT measurement for hybrid support models." },
      { icon: "LineChart", title: "Analytics & Optimization", description: "Conversation analytics, intent coverage mapping, drop-off analysis, and continuous improvement pipelines to maximize bot effectiveness." },
      { icon: "Lock", title: "Enterprise Security", description: "Data anonymization, PII masking, conversation encryption, and GDPR-compliant data handling for regulated industry deployments." },
    ],
    process: [
      { step: "01", title: "Intent Mapping", description: "Map user intents, define conversation flows, and gather training data." },
      { step: "02", title: "Bot Design", description: "Design conversation architecture, fallback handling, and persona." },
      { step: "03", title: "Build & Train", description: "Develop bot, integrate with backend systems, and train on domain data." },
      { step: "04", title: "Deploy & Optimize", description: "Multi-channel deployment with analytics and iterative optimization." },
    ],
    useCases: [
      "Customer support automation",
      "E-commerce shopping assistant",
      "HR FAQ and onboarding bot",
      "Healthcare appointment scheduling",
      "Banking query resolution",
      "Lead qualification bot",
      "IT help desk automation",
      "Insurance claim chatbot",
      "Internal knowledge assistant",
      "Product recommendation bot",
    ],
    faqs: [
      { q: "How is an LLM-powered chatbot different from a rule-based one?", a: "Rule-based bots follow decision trees and break on unexpected inputs. LLM-powered bots understand natural language, maintain context across turns, handle novel questions gracefully, and feel like talking to a knowledgeable human — while still respecting business guardrails." },
      { q: "Can the chatbot integrate with our CRM and ticketing systems?", a: "Yes. We integrate with Salesforce, HubSpot, Zendesk, Freshdesk, Jira, and most major CRM/ticketing platforms via APIs — enabling the bot to look up customer records, create tickets, and update order status in real time." },
      { q: "What happens when the bot doesn't know the answer?", a: "We design graceful fallback flows — the bot acknowledges the gap, offers related information, and escalates to a human agent with full conversation context so the user never has to repeat themselves." },
      { q: "How do you keep the chatbot accurate as our products change?", a: "We implement knowledge base refresh pipelines that re-index your documentation on a schedule or on-demand. For fine-tuned models, we design quarterly update cycles with regression testing to maintain accuracy as your product evolves." },
    ],
  },

  "ai-agents": {
    label: "AI Agents",
    titlePre: "Autonomous AI Agents That",
    titleGradient: "Get Things Done",
    headline: "Autonomous AI Agents",
    heroDescription:
      "We build multi-agent AI systems that plan, reason, use tools, and execute complex multi-step workflows autonomously. From single-purpose agents to enterprise-wide agentic platforms.",
    description:
      "AI agents that go beyond chatbots — they take action, use tools, browse the web, write code, call APIs, and complete complex tasks with minimal human supervision.",
    gradient: "from-orange-500 to-red-500",
    metrics: [
      { value: "80%", label: "Complex tasks automated" },
      { value: "5x", label: "Productivity multiplier" },
      { value: "70%", label: "Reduction in workflow cycle time" },
      { value: "Scalable", label: "From prototype to 1M+ tasks/month" },
    ],
    technologies: ["LangGraph", "AutoGen", "CrewAI", "OpenAI Assistants", "Anthropic Claude", "Tool APIs", "Python", "FastAPI"],
    features: [
      { icon: "Bot", title: "Multi-Agent Orchestration", description: "Architect systems of specialized AI agents that collaborate — planner, executor, critic, and memory agents working in coordinated workflows." },
      { icon: "Workflow", title: "Tool-Use & Action", description: "Agents that use real tools — web search, code execution, API calls, database queries, file operations, and browser automation." },
      { icon: "Brain", title: "Reasoning & Planning", description: "Long-horizon task planning with chain-of-thought reasoning, sub-task decomposition, and dynamic re-planning based on execution feedback." },
      { icon: "RefreshCw", title: "Memory & Context", description: "Long-term memory systems with semantic retrieval, episodic memory, and shared memory across agent networks for complex task execution." },
      { icon: "ShieldCheck", title: "Human-in-the-Loop", description: "Configurable oversight mechanisms — approval checkpoints, confidence thresholds, and audit trails for responsible agentic deployment." },
      { icon: "Monitor", title: "Agent Monitoring", description: "Real-time visibility into agent reasoning, actions, and outcomes. Full observability with trace logging and performance analytics." },
    ],
    process: [
      { step: "01", title: "Task Analysis", description: "Define agent objectives, tool requirements, and success criteria." },
      { step: "02", title: "Agent Design", description: "Design agent architecture, memory systems, and tool integration." },
      { step: "03", title: "Build & Evaluate", description: "Develop agents with systematic evaluation and safety testing." },
      { step: "04", title: "Production Deploy", description: "Deploy with monitoring, human oversight, and performance optimization." },
    ],
    useCases: [
      "Research & competitive analysis",
      "Automated code review agent",
      "Customer support ticket resolution",
      "Legal document review",
      "Financial analysis automation",
      "Multi-step procurement automation",
      "Content creation pipeline",
      "Data collection & enrichment",
      "Automated report generation",
      "DevOps automation agent",
    ],
    faqs: [
      { q: "What's the difference between an AI agent and a chatbot?", a: "Chatbots respond to queries. AI agents take action — they plan multi-step tasks, call external tools (APIs, browsers, code execution), make decisions based on intermediate results, and complete objectives autonomously without hand-holding." },
      { q: "How do you prevent agents from taking harmful actions?", a: "We implement sandboxed tool execution, action approval gates for high-stakes operations, confidence thresholds that trigger human review, rate limiting, and comprehensive audit logs. Safety is designed in from the architecture stage." },
      { q: "Which agent framework should we use — LangGraph, CrewAI, or AutoGen?", a: "LangGraph excels for deterministic, graph-based workflows. CrewAI is great for role-based multi-agent collaboration. AutoGen suits conversational agent networks. We select and often combine frameworks based on your specific task structure and reliability requirements." },
      { q: "How reliable are AI agents for production workloads?", a: "Reliability depends heavily on task complexity, tool reliability, and system design. We use structured outputs, retry logic, fallback strategies, and comprehensive testing to achieve 95–99%+ task completion rates for well-defined production agent workflows." },
    ],
  },

  "custom-software": {
    label: "Custom Software",
    titlePre: "Software Engineered Precisely",
    titleGradient: "for Your Business",
    headline: "Custom Software",
    heroDescription:
      "When off-the-shelf software doesn't cut it, we build exactly what you need. Custom software development with enterprise architecture, scalable design, and long-term maintainability.",
    description:
      "From internal tools to customer-facing platforms, we build software that fits your processes — not the other way around.",
    gradient: "from-slate-500 to-zinc-500",
    metrics: [
      { value: "100+", label: "Custom software projects" },
      { value: "98%", label: "On-time delivery rate" },
      { value: "3 years", label: "Average client relationship" },
      { value: "50%", label: "Faster delivery with our frameworks" },
    ],
    technologies: ["Next.js", "Node.js", "Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "AWS"],
    features: [
      { icon: "Code2", title: "Full-Stack Development", description: "End-to-end development from database design to frontend UI — all within a single, coordinated team for maximum velocity." },
      { icon: "Server", title: "API & Microservices", description: "Scalable API architectures, microservices design, and event-driven systems built for reliability and independent deployability." },
      { icon: "Lock", title: "Enterprise Integration", description: "Seamless integration with your ERP, CRM, HRMS, payment gateways, and third-party systems via APIs and webhooks." },
      { icon: "Gauge", title: "Performance Engineering", description: "Database optimization, caching strategies, and load testing to ensure software performs under real-world production conditions." },
      { icon: "ShieldCheck", title: "Security by Design", description: "OWASP-compliant development, penetration testing, vulnerability scanning, and secure coding practices throughout the project lifecycle." },
      { icon: "RefreshCw", title: "Maintenance & Evolution", description: "Post-launch support, feature development, tech debt reduction, and long-term architecture stewardship for growing systems." },
    ],
    process: [
      { step: "01", title: "Requirements", description: "Workshops to map business requirements, user stories, and system architecture." },
      { step: "02", title: "Design", description: "System design, API contracts, database schema, and UI wireframes." },
      { step: "03", title: "Build", description: "Agile development with weekly demos, code reviews, and CI/CD pipeline." },
      { step: "04", title: "Launch", description: "Production deployment, user training, and handover documentation." },
    ],
    useCases: [
      "Internal business tools",
      "Customer portal development",
      "ERP customization",
      "Marketplace platform",
      "Workflow automation software",
      "Reporting & analytics platform",
      "Integration middleware",
      "Legacy system replacement",
      "B2B SaaS product",
      "Admin dashboard",
    ],
    faqs: [
      { q: "How is custom software different from buying a SaaS product?", a: "SaaS products fit 80% of use cases at low cost but force you to adapt your processes to their limitations. Custom software is built around your exact workflows, integrates natively with your existing systems, and gives you full ownership and competitive differentiation." },
      { q: "How do you prevent scope creep?", a: "We use a structured discovery phase to lock requirements before development. Changes outside scope are logged, estimated, and approved as change orders. Weekly demos keep stakeholders aligned so surprises are rare." },
      { q: "What happens after launch — do you offer support?", a: "Yes. We offer post-launch support and maintenance packages covering bug fixes, security patches, performance monitoring, and feature development. Most clients maintain an ongoing relationship with us for 2–3 years after initial launch." },
      { q: "Can you take over a project another team started?", a: "Yes, we handle project rescues. We begin with a code and architecture audit, assess technical debt, and develop a stabilization and evolution plan. This is one of the most common ways new client relationships begin with us." },
    ],
  },

  "it-consulting": {
    label: "IT Consulting",
    titlePre: "Strategic Technology Guidance for",
    titleGradient: "Digital Leaders",
    headline: "IT Consulting",
    heroDescription:
      "Navigate digital transformation with confidence. Our IT consulting practice provides CTO-level strategic guidance, architecture reviews, and technology roadmaps without the overhead of a full-time executive.",
    description:
      "Pragmatic, business-outcome-focused technology advisory from practitioners who have built and scaled real systems.",
    gradient: "from-amber-500 to-orange-500",
    metrics: [
      { value: "40+", label: "Enterprise engagements" },
      { value: "30%", label: "Technology cost reduction (avg)" },
      { value: "2x", label: "Faster technology decisions" },
      { value: "CTO-level", label: "Strategic expertise on tap" },
    ],
    technologies: ["TOGAF", "AWS Well-Architected", "ITIL", "Agile", "DevOps", "Cloud Advisory", "Security Framework", "AI Strategy"],
    features: [
      { icon: "Brain", title: "AI Strategy & Roadmap", description: "Comprehensive AI adoption strategy — identifying opportunities, building business cases, and creating a phased implementation roadmap." },
      { icon: "Building2", title: "Enterprise Architecture", description: "Technology architecture review and design — ensuring your systems are scalable, maintainable, and aligned with business strategy." },
      { icon: "TrendingUp", title: "Digital Transformation", description: "End-to-end digital transformation advisory — from process digitization to full-scale technology platform modernization." },
      { icon: "ShieldCheck", title: "Technology Due Diligence", description: "Pre-acquisition technical assessments, code quality reviews, architecture evaluation, and risk identification for M&A scenarios." },
      { icon: "Gauge", title: "Performance & Cost Optimization", description: "Technology cost reduction, vendor negotiation strategy, build-vs-buy analysis, and technology rationalization programs." },
      { icon: "Users", title: "Technology Leadership Advisory", description: "Fractional CTO services, technology team structuring, hiring strategy, and engineering culture development." },
    ],
    process: [
      { step: "01", title: "Current State", description: "Assess current technology landscape, capabilities, and pain points." },
      { step: "02", title: "Strategy Design", description: "Define target architecture, technology stack, and transformation roadmap." },
      { step: "03", title: "Planning", description: "Business cases, vendor evaluation, team structure, and timeline." },
      { step: "04", title: "Advisory Support", description: "Ongoing advisory during implementation with course correction as needed." },
    ],
    useCases: [
      "AI readiness assessment",
      "Technology stack evaluation",
      "Cloud migration strategy",
      "Digital transformation roadmap",
      "Fractional CTO services",
      "M&A technology due diligence",
      "Engineering team scaling",
      "Build vs. buy analysis",
      "Vendor selection advisory",
      "Technology risk assessment",
    ],
    faqs: [
      { q: "What is a Fractional CTO and do we need one?", a: "A fractional CTO provides senior technology leadership part-time — typically 1–3 days per week. It's ideal for companies that need CTO-level strategy, team leadership, or vendor oversight but aren't ready for a full-time executive hire at a CTO salary." },
      { q: "How do you approach technology due diligence for M&A?", a: "We review code quality, architecture, security posture, technical debt, team capabilities, and scalability risks. We deliver a structured report with a risk rating, deal-breaker identification, and post-acquisition remediation roadmap within 2–3 weeks." },
      { q: "Can you help us evaluate vendors and build a shortlist?", a: "Yes. Vendor evaluation is a common consulting engagement. We define requirements, score vendors against weighted criteria, run proof-of-concept evaluations, and deliver an objective recommendation with total cost of ownership analysis." },
      { q: "What does a digital transformation engagement look like?", a: "We start with a current-state assessment (processes, technology, team), then design a target state and multi-year transformation roadmap with prioritized initiatives, investment requirements, and expected business outcomes. We can then support execution as an ongoing advisory partner." },
    ],
  },

  "staff-augmentation": {
    label: "Staff Augmentation",
    titlePre: "Elite AI & Engineering Talent",
    titleGradient: "On Demand",
    headline: "Staff Augmentation",
    heroDescription:
      "Scale your team instantly with pre-vetted AI engineers, data scientists, ML researchers, and full-stack developers. No long hiring cycles. No HR overhead. Just excellent talent, ready when you need it.",
    description:
      "Dedicated AI and engineering talent that integrates seamlessly with your team — working in your tools, your timezone, and aligned to your engineering culture.",
    gradient: "from-rose-500 to-pink-500",
    metrics: [
      { value: "48 hrs", label: "Time to first candidate interview" },
      { value: "95%", label: "Trial-to-long-term conversion" },
      { value: "50+", label: "AI experts available" },
      { value: "0 costs", label: "No recruitment or HR fees" },
    ],
    technologies: ["Python", "PyTorch", "TensorFlow", "LangChain", "Next.js", "React", "Node.js", "AWS/Azure/GCP"],
    features: [
      { icon: "Brain", title: "AI & ML Engineers", description: "Senior ML engineers, data scientists, and AI researchers with hands-on experience building production AI systems across diverse industries." },
      { icon: "Globe", title: "Full-Stack Developers", description: "Experienced full-stack engineers specializing in Next.js, React, Node.js, and Python — ready to integrate with your existing codebase." },
      { icon: "Database", title: "Data Engineers", description: "Data engineering specialists for building pipelines, data platforms, and analytics infrastructure on modern cloud data stacks." },
      { icon: "Palette", title: "UI/UX Designers", description: "Senior product designers skilled in Figma, design systems, and user research — available for product or project-specific engagements." },
      { icon: "ShieldCheck", title: "Vetted & Background Checked", description: "Every engineer goes through technical assessments, portfolio reviews, communication evaluation, and background verification before joining your team." },
      { icon: "RefreshCw", title: "Flexible Engagement Models", description: "Part-time, full-time, project-based, or multi-resource team arrangements. Scale up or down as your project needs evolve — no lock-in." },
    ],
    process: [
      { step: "01", title: "Requirements", description: "Define skills, experience level, timezone, and engagement duration." },
      { step: "02", title: "Matching", description: "Present pre-vetted candidates within 48 hours from our talent network." },
      { step: "03", title: "Interview & Trial", description: "Interview candidates and run a paid trial sprint before full commitment." },
      { step: "04", title: "Onboard & Scale", description: "Seamless onboarding to your team with ongoing support from ArlioTech." },
    ],
    useCases: [
      "ML engineer for AI product",
      "Generative AI specialist",
      "Data scientist for analytics team",
      "Frontend engineer (React/Next.js)",
      "Backend developer (Node/Python)",
      "Cloud/DevOps engineer",
      "NLP specialist",
      "Computer vision engineer",
      "UI/UX designer",
      "Technical project manager",
    ],
    faqs: [
      { q: "How quickly can we get someone started?", a: "We present pre-vetted candidates within 48 hours of receiving your requirements. After your interview and a paid trial sprint (typically 1–2 weeks), the engineer can be fully onboarded and productive within 2–3 weeks of initial contact." },
      { q: "What if the engineer isn't the right fit?", a: "We stand behind our placements. If someone isn't working out within the first 30 days, we replace them at no additional cost. Our 95% trial-to-long-term conversion rate means this rarely happens, but we make it risk-free." },
      { q: "Do your engineers work in our timezone?", a: "Yes. We have engineers available across IST, GMT, and US timezones. For most engagements, we ensure at least 4–6 hours of overlap with your core team hours for real-time collaboration." },
      { q: "Who manages the engineer — us or ArlioTech?", a: "You manage the day-to-day work and priorities — the engineer is fully dedicated to your team and follows your processes. ArlioTech handles HR, payroll, benefits, and provides a technical account manager who does monthly check-ins to ensure quality." },
    ],
  },
};
